services:
  postgres:
    image: postgres:16
    container_name: synchroflow_db
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - synchroflow-net

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: synchroflow_mq
    hostname: rabbitmq
    ports:
      # AMQP protocol port
      - "5672:5672"
      # HTTP management UI
      - "15672:15672"
    environment:
      # Default user and password
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DISK_FREE_LIMIT: "50MB"
    networks:
      - synchroflow-net

volumes:
  postgres_data:

networks:
  synchroflow-net:
    driver: bridge