export const CanonicalIngestionFailureReason = {
  MISSING_PRODUCT_ID: 'MISSING_PRODUCT_ID',
  MISSING_VARIANT_ID: 'MISSING_VARIANT_ID',
  UNRESOLVED_VARIANT: 'UNRESOLVED_VARIANT',
  UNRESOLVED_PRODUCT: 'UNRESOLVED_PRODUCT',
  MISSING_PRICING: 'MISSING_PRICING',
  MISSING_CURRENCY: 'MISSING_CURRENCY',
  MISSING_TOTALS: 'MISSING_TOTALS',
  PRODUCT_INGESTION_LAG: 'PRODUCT_INGESTION_LAG',
  UNKNOWN_CANONICAL_VIOLATION: 'UNKNOWN_CANONICAL_VIOLATION',
} as const;

export type CanonicalIngestionFailureReason =
  (typeof CanonicalIngestionFailureReason)[keyof typeof CanonicalIngestionFailureReason];
