/* modules/order-nexus-test/src/ui/ModuleEntry.tsx
 * Auto-generated by scaffold
 */

import { registerModule } from 'runtime/registerModule';
import { registerRoute } from 'runtime/registerRoute';

const OrderNexusTestHome = () => {
  return null;
};

export const descriptor = {
  id: "order-nexus-test",
  name: "OrderNexusTest",
  version: "0.1.0",
  routes: [
    {
      id: "order-nexus-test-home",
      key: "order-nexus-test-home",
      name: "OrderNexusTest Home",
      path: "/order-nexus-test",
      component: OrderNexusTestHome,
      requiredModuleId: "order-nexus-test",
      order: 100
    }
  ],
  navItems: [
    {
      id: "order-nexus-test-home",
      title: "OrderNexusTest",
      path: "/order-nexus-test",
      order: 50
    }
  ]
};

export async function register(host: any) {
  // register module metadata with host runtime
  registerModule({
    id: descriptor.id,
    name: descriptor.name,
    version: descriptor.version ?? '0.0.0'
  });

  // register the module's routes so host can wire them
  if (Array.isArray(descriptor.routes)) {
    for (const r of descriptor.routes) {
      registerRoute(r);
    }
  }

  // register nav items using host API
  if (Array.isArray(descriptor.navItems) && host?.addNavItem) {
    for (const n of descriptor.navItems) {
      host.addNavItem(n);
    }
  }

  // return lifecycle hooks
  return {
    mount: () => null,
    onMount: async () => {},
    onActivate: async () => {},
    onDeactivate: async () => {},
    onUnmount: async () => {}
  };
}

// Descriptor already contains `id` — export it directly to avoid duplicate-id
// object-literals (and satisfy the checker).
export default descriptor;