/* modules/my-test-module/src/ui/ModuleEntry.tsx
 * Auto-generated by scaffold
 */

import { registerModule } from 'runtime/registerModule';
import { registerRoute } from 'runtime/registerRoute';

const MyTestModuleHome = () => {
  return null;
};

export const descriptor = {
  id: "my-test-module",
  name: "MyTestModule",
  version: "0.1.0",
  routes: [
    {
      id: "my-test-module-home",
      key: "my-test-module-home",
      name: "MyTestModule Home",
      path: "/my-test-module",
      component: MyTestModuleHome,
      requiredModuleId: "my-test-module",
      order: 100
    }
  ],
  navItems: [
    {
      id: "my-test-module-home",
      title: "MyTestModule",
      path: "/my-test-module",
      order: 50
    }
  ]
};

export async function register(host: any) {
  // register module metadata with host runtime
  registerModule({
    id: descriptor.id,
    name: descriptor.name,
    version: descriptor.version ?? '0.0.0'
  });

  // register the module's routes so host can wire them
  if (Array.isArray(descriptor.routes)) {
    for (const r of descriptor.routes) {
      registerRoute(r);
    }
  }

  // register nav items using host API
  if (Array.isArray(descriptor.navItems) && host?.addNavItem) {
    for (const n of descriptor.navItems) {
      host.addNavItem(n);
    }
  }

  // return lifecycle hooks
  return {
    mount: () => null,
    onMount: async () => {},
    onActivate: async () => {},
    onDeactivate: async () => {},
    onUnmount: async () => {}
  };
}

export default { register, descriptor };
