//apps/backend/src/services/opsIntel/types.ts
/**
 * This is the backend definition for a Proactive Insight.
 * This object will be generated by a BusinessRule and then
 * sent over the SSE stream to the frontend.
 */
export interface ProactiveInsight {
  id: string;
  type: 'alert' | 'recommendation' | 'opportunity' | 'celebration';
  title: string;
  message: string;
  urgency: 'high' | 'medium' | 'low';
  timestamp: number;
  source: 'inventory' | 'orders' | 'customers' | 'marketing' | 'shipping';
  
  // This is the data the frontend will use to build the
  // 'suggestedActions' (which are OpsActions)
  actionPayload: {
    // e.g., 'nav-order-detail', 'open-customer-contact'
    actionId: string;
    // e.g., { orderId: '123' }
    context: Record<string, any>;
  }[];
}