import type { Knex } from 'knex';

/**
 * ALERTS TABLE
 * ------------
 * Persistent operator-facing signal inbox.
 *
 * PURPOSE:
 * - Unified surface for all system-generated signals
 * - Ranked by urgency and commercial impact
 * - Dismissible per operator session
 * - Source-agnostic: constraints, decisions, projection health
 *
 * INVARIANTS:
 * - One alert per (shop_id, alert_key) — alert_key is deterministic
 * - Alerts are upserted, not duplicated
 * - resolved_at set when signal clears — UI auto-dismisses
 */
export async function up(knex: Knex): Promise<void> {
  await knex.schema.createTable('alerts', (table) => {
    table.uuid('id').primary().defaultTo(knex.raw('gen_random_uuid()'));

    table.integer('shop_id').notNullable();

    /**
     * DETERMINISTIC ALERT KEY
     * -----------------------
     * Uniqueness anchor per shop.
     * Format: {source}:{entity_id}:{alert_type}
     * Example: constraint:order-uuid:operational
     *          snapshot:shop-1:sla_risk
     */
    table.string('alert_key').notNullable();
    table.unique(['shop_id', 'alert_key']);

    /**
     * ALERT CLASSIFICATION
     * --------------------
     * source: where the signal originated
     * alert_type: what kind of signal it is
     */
    table.string('source').notNullable();
    // constraint | decision | snapshot | projection_health
    table.string('alert_type').notNullable();
    // sla_breach | inventory_short | customer_block | revenue_at_risk | system_degraded

    /**
     * SEVERITY
     * --------
     * critical | warning | info
     * Maps to UI color and ordering
     */
    table.string('severity').notNullable().defaultTo('warning');

    /**
     * OPERATOR-FACING CONTENT
     * -----------------------
     * title: short, operator-vocabulary label
     * message: one-sentence explanation
     */
    table.string('title').notNullable();
    table.text('message').notNullable();

    /**
     * ENTITY CONTEXT
     * --------------
     * Optional reference to the affected entity (order, shop, etc.)
     */
    table.string('entity_id').nullable();
    table.string('entity_type').nullable(); // order | shop | variant

    /**
     * COMMERCIAL SIGNAL
     * -----------------
     * Revenue impact if available — used for ranking
     */
    table.decimal('revenue_impact', 14, 2).nullable();

    /**
     * LIFECYCLE
     * ---------
     * is_active: false when signal clears (auto-resolved)
     * dismissed_at: operator manually dismissed
     * resolved_at: system determined signal no longer applies
     */
    table.boolean('is_active').notNullable().defaultTo(true);
    table.timestamp('dismissed_at', { useTz: true }).nullable();
    table.timestamp('resolved_at', { useTz: true }).nullable();

    /**
     * CONSEQUENCE TAXONOMY (D1)
     * -------------------------
     * category: primary UI grouping — consequence, not technical severity
     * audience: role-scoped surface visibility
     * Values: revenue_at_risk | stock_reorder | money_margin |
     *         supplier_inbound | warehouse_floor | data_trust
     */
    table.string('category').nullable();
    table.string('audience').notNullable().defaultTo('all');
    // operator | owner | all

    /**
     * LIFECYCLE — ACKNOWLEDGE / SNOOZE / RESOLVE (ALR-07)
     * ----------------------------------------------------
     * Replaces dismiss (KI-2: aggregator re-upserted is_active=true on
     * every snapshot cycle, making dismiss silently ineffective).
     *
     * acknowledged_at/by : operator has seen it; stays in Inbox, muted styling
     * snoozed_until      : hidden from Inbox until timestamp, then returns
     * escalated_at       : promoted to owner/admin visibility
     * rule_id            : set when generated by a configurable rule (ALR-11)
     */
    table.timestamp('acknowledged_at', { useTz: true }).nullable();
    table.integer('acknowledged_by').nullable();
    // references users.id — no hard FK; user records may be soft-deleted
    table.timestamp('snoozed_until', { useTz: true }).nullable();
    table.timestamp('escalated_at', { useTz: true }).nullable();
    table.uuid('rule_id').nullable();
    // references shop_alert_rules.id — gated until rules engine ships (ALR-11)

    table.timestamp('created_at', { useTz: true })
      .notNullable()
      .defaultTo(knex.fn.now());
    table.timestamp('updated_at', { useTz: true })
      .notNullable()
      .defaultTo(knex.fn.now());

    table.index(['shop_id', 'is_active'],     'idx_alerts_shop_active');
    table.index(['shop_id', 'severity'],      'idx_alerts_shop_severity');
    table.index(['shop_id', 'category'],      'idx_alerts_shop_category');
    table.index(['shop_id', 'snoozed_until'], 'idx_alerts_shop_snoozed');
  });

  /**
   * RLS (MANDATORY)
   * ---------------
   * Canonical variable: app.current_tenant::int
   */
  await knex.raw(`
    ALTER TABLE alerts ENABLE ROW LEVEL SECURITY;
  `);

  await knex.raw(`
    CREATE POLICY alerts_tenant_isolation
    ON alerts
    USING (shop_id = current_setting('app.current_tenant')::int)
    WITH CHECK (shop_id = current_setting('app.current_tenant')::int);
  `);
}

export async function down(knex: Knex): Promise<void> {
  await knex.raw(`DROP POLICY IF EXISTS alerts_tenant_isolation ON alerts;`);
  await knex.schema.dropTableIfExists('alerts');
}