import { Knex } from 'knex';

export async function up(knex: Knex): Promise<void> {

  // 1️⃣ Create ENUM (idempotent-safe)
  await knex.schema.raw(`
    DO $$
    BEGIN
      IF NOT EXISTS (
        SELECT 1 FROM pg_type WHERE typname = 'warehouse_location_type'
      ) THEN
        CREATE TYPE warehouse_location_type AS ENUM (
          'warehouse',
          'lane',
          'shelf',
          'bin'
        );
      END IF;
    END$$;
  `);

  // 2️⃣ Create warehouse_locations table
  await knex.schema.createTable('warehouse_locations', (table) => {
    table
      .string('location_code', 255)
      .notNullable();

    table
      .integer('shop_id')
      .notNullable()
      .references('id')
      .inTable('shops')
      .onDelete('CASCADE');

    table
      .string('parent_location_code', 255)
      .nullable()
      .references('location_code')
      .inTable('warehouse_locations')
      .onDelete('SET NULL');

    table
      .string('external_location_id', 255)
      .nullable(); // Shopify location_id mapping

    table
      .specificType('type', 'warehouse_location_type')
      .notNullable();

    table
      .boolean('active')
      .notNullable()
      .defaultTo(true);

    table.timestamp('created_at', { useTz: true })
      .notNullable()
      .defaultTo(knex.fn.now());

    table.timestamp('updated_at', { useTz: true })
      .notNullable()
      .defaultTo(knex.fn.now());

    table.primary(['location_code']);

    table
      .string('barcode', 255)
      .nullable()
      .comment('System-generated scannable barcode for this location (e.g. LOC-A01-03-B). Generated by floor-planning module. Used by operators to confirm location during stow/pick.');

    /**
     * max_capacity: soft unit capacity threshold for this location.
     * Null = unlimited. When stow confirm causes stowed unit count to
     * exceed this value, a problem_center_tasks row is created for
     * operator audit (bin_over_capacity). Never a hard block — operator
     * can always override. (WEB-STOW-UNIT-01)
     */
    table.integer('max_capacity').nullable();
    table.unique(['shop_id', 'barcode'], 'warehouse_locations_barcode_unique');

    table.unique(['shop_id', 'location_code']);
    table.unique(['shop_id', 'external_location_id'], 'warehouse_external_location_unique');
    table.index(['shop_id']);
  });

  /**
   * RLS INVARIANT
   * -------------
   * warehouse_locations is strictly tenant-scoped via shop_id.
   *
   * This table participates in composite FK:
   *   inventory_movements (shop_id, location_code)
   *
   * Any cross-tenant leakage here corrupts:
   * - inventory allocation
   * - fulfillment routing
   *
   * DO NOT weaken this policy.
   */

  // --- RLS: Enforce tenant isolation ---
  await knex.raw(`
    ALTER TABLE warehouse_locations ENABLE ROW LEVEL SECURITY;
    ALTER TABLE warehouse_locations FORCE ROW LEVEL SECURITY;
  `);

  await knex.raw(`
    DROP POLICY IF EXISTS warehouse_locations_tenant_isolation_policy ON warehouse_locations;
  `);

  await knex.raw(`
    CREATE POLICY warehouse_locations_tenant_isolation_policy
    ON warehouse_locations
    USING (
      shop_id = current_setting('app.current_tenant')::int
    );
  `);
}

export async function down(knex: Knex): Promise<void> {
  await knex.schema.dropTableIfExists('warehouse_locations');

  await knex.schema.raw(`
    DROP TYPE IF EXISTS warehouse_location_type;
  `);
}
