import { Knex } from 'knex';

/**
 * MIGRATION 0089 — create_push_subscriptions
 * --------------------------------------------
 * Stores Web Push and Expo push tokens per user per device.
 *
 * Notification dispatch (notificationDispatch.service.ts) queries
 * this table to fan out to all active subscriptions for a user.
 *
 * device_type = 'web'  → Web Push API (endpoint + p256dh + auth)
 * device_type = 'expo' → Expo Push API → APNs / FCM (expo_push_token)
 *
 * Invariants:
 * - One row per (user_id, endpoint) for web subscriptions
 * - One row per (user_id, expo_push_token) for expo subscriptions
 * - Rows are upserted on re-subscription — no duplicates
 * - RLS enforced via shop_id
 */
export async function up(knex: Knex): Promise<void> {
  await knex.raw(`
    DO $$
    BEGIN
      IF NOT EXISTS (
        SELECT 1 FROM pg_type WHERE typname = 'push_device_type'
      ) THEN
        CREATE TYPE push_device_type AS ENUM ('web', 'expo');
      END IF;
    END$$;
  `);

  await knex.schema.createTable('push_subscriptions', (table) => {
    table
      .uuid('id')
      .primary()
      .notNullable()
      .defaultTo(knex.raw('gen_random_uuid()'));

    table
      .integer('shop_id')
      .notNullable()
      .references('id')
      .inTable('shops')
      .onDelete('CASCADE');

    table
      .integer('user_id')
      .notNullable()
      .references('id')
      .inTable('users')
      .onDelete('CASCADE');

    table
      .specificType('device_type', 'push_device_type')
      .notNullable();

    /**
     * WEB PUSH FIELDS (device_type = 'web')
     * --------------------------------------
     * Generated by browser Push API subscription.
     * endpoint is unique per browser/device combination.
     */
    table.text('endpoint').nullable();
    table.text('p256dh').nullable();
    table.text('auth').nullable();

    /**
     * EXPO PUSH FIELDS (device_type = 'expo')
     * ----------------------------------------
     * Generated by Expo.Notifications.getExpoPushTokenAsync().
     * Rotates on app reinstall — upsert on each app launch.
     */
    table.text('expo_push_token').nullable();

    table.timestamp('created_at', { useTz: true })
      .notNullable()
      .defaultTo(knex.fn.now());

    table.timestamp('updated_at', { useTz: true })
      .notNullable()
      .defaultTo(knex.fn.now());

    // Prevent duplicate web subscriptions per user
    table.unique(['user_id', 'endpoint']);

    // Prevent duplicate expo subscriptions per user
    table.unique(['user_id', 'expo_push_token']);

    table.index(['shop_id', 'user_id']);
    table.index(['shop_id', 'device_type']);
  });

  await knex.raw(`
    ALTER TABLE push_subscriptions ENABLE ROW LEVEL SECURITY;
    ALTER TABLE push_subscriptions FORCE ROW LEVEL SECURITY;
  `);

  await knex.raw(`
    DROP POLICY IF EXISTS push_subscriptions_tenant_isolation_policy ON push_subscriptions;
  `);

  await knex.raw(`
    CREATE POLICY push_subscriptions_tenant_isolation_policy
    ON push_subscriptions
    USING (
      shop_id = current_setting('app.current_tenant')::int
    );
  `);
}

export async function down(knex: Knex): Promise<void> {
  await knex.schema.dropTableIfExists('push_subscriptions');
  await knex.raw(`DROP TYPE IF EXISTS push_device_type;`);
}